Code Refactor to Adhere to PEP-8 Function and Variable Naming Conventions
CruiseDevice/twweet-cli pull request #69
Opened 2018-05-11 18:53 UTC by jgarciabu

I went through all the code and refactored the function and variable names to adhere to PEP-8 naming conventions. CamelCase names have been replaced by lowercase_names_separated_by_underscores for functions and variables. Classes using CamelCase have been left untouched as classes can use CamelCase per PEP-8.

2018-06-22 06:15 UTC, omeshomes approved these changes
This edit looks good! Makes the code much more readable and reusable

2018-06-22 06:15 UTC, omeshomes commented on twweet_cli/Twweeter.py
> +    def read_time_line(self):
timeline is one word, i think read_timeline would be better

2018-06-22 06:21 UTC, omeshomes requested changes
Looks like there are conflicts with the base branch--maybe try pulling any changes from remote and commit those changes?

2018-06-22 12:54 UTC, jgarciabu commented
Let me know if I need to revisit, but I think it's all set! This is one of my first open source contributions so I appreciate your encouraging words.

2018-06-30 15:06 UTC, merged

2018-06-30 15:06 UTC, nithinswarrier commented
This ought to work! Good work